### ISSUE TITLE
Transitions cause panic if a new transition is called for during ongoing transition

### ISSUE THREAD

**Issue by harbdog** [joelschutz/stagehand#7]
All of the examples currently in the master branch throw the following panic if you right-click to switch with transition during a transition that has not yet completed. If you wait for the transition to finish to click again there is no panic. Using Go version 1.20.13 on Linux Mint 21.3.

The easiest example to reproduce this on is `examples/timed` since it has a very long transition time, but the others experienced the same panic.

```bash
go run examples/timed/main.go
panic: interface conversion: *stagehand.SlideTransition[main.State] is not stagehand.Scene[main.State]: missing method Load

goroutine 7 [running]:
github.com/joelschutz/stagehand.(*SceneManager[...]).SwitchWithTransition(0x83b7e0, {0x838320, 0xc000405ef0}, {0x838260, 0xc00012f2c0})
	/home/eric/git/stagehand/manager.go:24 +0x54
main.(*FirstScene).Update(0xc0001a8690)
	/home/eric/git/stagehand/examples/timed/main.go:52 +0xa6
github.com/joelschutz/stagehand.(*BaseTransition[...]).Update(0x5fa58d)
	/home/eric/git/stagehand/transition.go:30 +0x29
github.com/joelschutz/stagehand.(*SlideTransition[...]).Update(0x1?)
	/home/eric/git/stagehand/transition.go:167 +0x6f
github.com/joelschutz/stagehand.(*SceneManager[...]).Update(...)
	/home/eric/git/stagehand/manager.go:45
github.com/hajimehoshi/ebiten/v2.(*gameForUI).Update(0xc0001cc000)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/gameforui.go:155 +0x29
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0000ebd50, {0x83a8a0, 0xc000194800}, 0x1, 0x4084000000000000, 0x407e000000000000, 0x414738?, 0xb01ca0, 0x0?)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/context.go:138 +0x3ca
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc00028ca20?, {0x83a8a0, 0xc000194800}, 0xffffffffffffffff?, 0x1?, 0x0?, 0x0?)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/context.go:73 +0x85
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0xb01ca0)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/ui_glfw.go:1084 +0x1f9
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0xb01ca0)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/ui_glfw.go:1044 +0x99
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/run_glfw_notsinglethread.go:57 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/eric/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/eric/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
exit status 2
```

**Comment by harbdog** [comment]
Forgot that the director panic is slightly different, here's its stack trace:

```bash
go run examples/director/main.go 
panic: interface conversion: *stagehand.SlideTransition[main.State] is not stagehand.Scene[main.State]: missing method Load

goroutine 67 [running]:
github.com/joelschutz/stagehand.(*SceneDirector[...]).ProcessTrigger(0x83b760, 0x0)
	/home/eric/git/stagehand/director.go:27 +0x59
main.(*SecondScene).Update(0xc000293530)
	/home/eric/git/stagehand/examples/director/main.go:74 +0x5d
github.com/joelschutz/stagehand.(*BaseTransition[...]).Update(0x5fa44d)
	/home/eric/git/stagehand/transition.go:30 +0x29
github.com/joelschutz/stagehand.(*SlideTransition[...]).Update(0x1?)
	/home/eric/git/stagehand/transition.go:167 +0x6f
github.com/joelschutz/stagehand.(*SceneManager[...]).Update(...)
	/home/eric/git/stagehand/manager.go:49
github.com/hajimehoshi/ebiten/v2.(*gameForUI).Update(0xc0002b2230)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/gameforui.go:155 +0x29
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc0002afce0, {0x83b240, 0xc00014e700}, 0x1, 0x4084000000000000, 0x407e000000000000, 0x414738?, 0xb01ca0, 0x0?)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/context.go:138 +0x3ca
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc0001ac740?, {0x83b240, 0xc00014e700}, 0x47?, 0xc0000d7728?, 0x4239b0?, 0x20?)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/context.go:73 +0x85
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0xb01ca0)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/ui_glfw.go:1084 +0x1f9
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0xb01ca0)
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/ui_glfw.go:1044 +0x99
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
	/home/eric/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.3/internal/ui/run_glfw_notsinglethread.go:57 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/eric/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/eric/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
exit status 2

```
